services:
  # --- Наш Бэкенд-сервис ---
  # Он будет приватным, недоступным из интернета напрямую.
  - type: pvt # pvt = Private Service (Приватный сервис)
    name: backend # Это имя станет его сетевым адресом, например http://backend:3000
    env: docker # Указываем, что мы используем Docker для сборки
    dockerfilePath: ./backend/Dockerfile # Путь к его Dockerfile от корня репозитория

    # Переменные окружения для бэкенда
    envVars:
      - key: MONGO_URI
        # Это специальное поле говорит Render: "Возьми значение для MONGO_URI
        # из секретного хранилища, которое пользователь настроит в веб-интерфейсе".
        # Это безопасно!
        fromEnvironmentVar: MONGO_URI
      - key: PORT
        # Жестко указываем порт внутри контейнера. Наш Nginx настроен
        # проксировать именно на порт 3000.
        value: 3000

  # --- Наш Фронтенд-сервис (Nginx) ---
  # Это будет наша единственная публичная точка входа.
  - type: web # web = Web Service (Публичный веб-сервис)
    name: frontend # Имя сервиса
    env: docker
    dockerfilePath: ./frontend/Dockerfile

    # Render автоматически пробросит порт 80 из контейнера наружу
    # и предоставит для него HTTPS-адрес.

    # Проверка здоровья сервиса. Render будет периодически отправлять
    # GET-запрос по этому пути, чтобы убедиться, что наш Nginx жив.
    healthCheck:
      path: /