services:
  - type: web 
    name: backend 
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: MONGO_URI
        value: "" 

  # --- Наш Фронтенд-сервис (Nginx) ---
  - type: web
    name: frontend 
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    healthCheckPath: /