services:
  # --- Наш Бэкенд-сервис ---
  - type: web
    name: habit-tracker-backend
    runtime: docker
    repo: https://github.com/cookiesbro/habit-tracker
    rootDir: backend
    envVars:
      - key: MONGO_URI
        sync: false # Мы добавим значение вручную через дашборд

  # --- Наш Фронтенд-сервис ---
  - type: static_site  # <-- Вот он, правильный тип для статики с редиректами
    name: habit-tracker-frontend
    repo: https://github.com/cookiesbro/habit-tracker
    rootDir: frontend
    # Для static_site не нужен runtime, у него есть publishDir
    publishDir: . 
    # И самое главное - блок routes
    routes:
      - type: rewrite
        source: /api/:path*
        destination: https://habit-tracker-backend-ni7z.onrender.com/api/$1