services:
  - type: web   
    name: habit-tracker-backend
    runtime: docker 
    repo: https://github.com/cookiesbro/habit-tracker
    rootDir: backend
    envVars:
      - key: MONGO_URI
        fromSecret: true 
  - type: web
    name: habit-tracker-frontend
    runtime: static
    repo: https://github.com/cookiesbro/habit-tracker 
    rootDir: frontend
    routes:
      - type: rewrite
        source: /api/(.*)
        destination: https://habit-tracker-backend-ni7z.onrender.com/api/$1